#### Targets settings

TOP = ../../../../../..

PACKAGE = edu/jach/qt/djava

SOURCES = \
	CSOPathResponseHandler.java \
	MonitorResponse.java \
	QT_MonResponse.java \
	TELPathResponseHandler.java

include ${TOP}/Makefile
