####
#### Java Makefile automatically generated by jmaker 2.0
#### Creation date: Wed May 29 09:00:03 2002
####

include		makeInclude

#### Java compiler settings

#### Targets settings
#CLASS_FILES   =  No class files in this dir
SUBDIRS       = src
SUBDIRS_CLEAN = $(patsubst %,%.clean,$(SUBDIRS))
SUBDIRS_MAKE  = $(patsubst %,%.make,$(SUBDIRS))

#### Main targets

# Default
all: $(CLASS_FILES) $(SUBDIRS_MAKE) $(INSTALL)/icons

# Cleanup
clean: $(SUBDIRS_CLEAN)
	$(RM) *.class
	@echo "Cleanup done."

# Rebuild
build: clean all
	@echo "Rebuild done."

#### Aux targets

# Files compilation
%.class: %.java
	$(JAVAC) $(JAVAC_FLAGS) $<

# Sub-directories compilation
%.make:
	$(MAKE) -k -C $(subst .make,,$@)

# Sub-directories cleanup
%.clean:
	$(MAKE) -k -C $(subst .clean,,$@) clean

# Phony Targets
.PHONY: clean build help

#### Help
help:
	@echo "Usage: make [targets...]"
	@echo ""
	@echo "where targets include:"
	@echo ""
	@echo "  help           display this help"
	@echo "  all            compile all (default)"
	@echo "  clean          remove all class files"
	@echo "  build          rebuild all inconditionnally"
	@echo "  <class file>   compile the given file"
	@echo "  <subdir>.make  compile the given subdir"
	@echo "  <subdir>.clean clean the given subdir"

