####
#### Java Makefile automatically generated by jmaker 2.0
#### Creation date: Wed May 29 09:00:03 2002
####

include		makeInclude

#### Java compiler settings

#### Targets settings
#CLASS_FILES   =  No class files in this dir
LOCALDIR      = $(PWD)
ROOTDIR       = src/main/edu/jach/qt
#
# DO NOT CHANGE THE ORDER BELOW
#
SUBDIRS       = \
	$(ROOTDIR)/utils \
	$(ROOTDIR)/gui \
	$(ROOTDIR)/djava \
	$(ROOTDIR)/app

FRC=force_rebuild

#### Main targets

# Default
all: local

install: buildsys $(FRC)
	for dir in $(SUBDIRS); do \
		cd $$dir; $(MAKE) "INSTALL=true" FRC=force_rebuild;cd $(LOCALDIR); \
	done
	$(JAR) cf $(INSTALLDIR)/lib/qt.jar -C $(SYSTEM_CLASSDIR) edu
	@ echo "Installing icons..."
	@ $(CP) icons/*.* $(INSTALLDIR)/icons
	@ echo "Installing scripts..."
	@ $(CP) bin/qt $(INSTALLDIR)/bin
	@ echo "Installing config files..."
	@ $(CP) -r config/* $(INSTALLDIR)/config
	@ echo "Installing jar files..."
	@ $(CP) -r lib/*.jar $(INSTALLDIR)/lib

local:
	for dir in $(SUBDIRS); do \
		cd $$dir; $(MAKE) FRC=force_rebuild; cd $(LOCALDIR); \
	done
	$(JAR) cf qt.jar -C install/classes edu

force_rebuild:

buildsys:
	@ echo "Installing in directory " $(INSTALLDIR)
	@ echo "To change directory, modify VERSION in file makeInclude."
	@ echo "Installation in 5 seconds - type cntrl-C to abort."
	@ sleep 5
	@ if [[ ! -d $(INSTALLDIR) ]]; then \
		mkdir -p $(INSTALLDIR)/bin; \
		mkdir -p $(INSTALLDIR)/classes; \
		mkdir -p $(INSTALLDIR)/config; \
		mkdir -p $(INSTALLDIR)/icons; \
		mkdir -p $(INSTALLDIR)/lib; \
	fi

clean:
	$(RM) qt.jar
	for dir in $(SUBDIRS); do \
		cd $$dir; $(MAKE) clean; cd $(LOCALDIR); \
	done


sysclean:
	$(RM) $(INSTALLDIR)/lib/qt.jar
	for dir in $(SUBDIRS); do \
		cd $$dir; $(MAKE) sysclean; cd $(LOCALDIR); \
	done


#### Help
help:
	@echo "Usage: make [targets...]"
	@echo ""
	@echo "where targets include:"
	@echo ""
	@echo "  help           display this help"
	@echo "  all            compile all locally (default)"
	@echo "  clean          remove all local class and jar files"
	@echo "  install        compile all and install"
	@echo "  sysclean       remove cll installed class and jar files"

