BUILD     = ../../../../../../..
include	    $(BUILD)/makeInclude

PACKAGE	    = $(QT_PACKAGE)/gui

#### Targets settings

SOURCES = \
	../app/Subject.java \
	../app/Observer.java \
	../app/Querytool.java \
	WidgetDataBag.java \
	WidgetPanel.java \
	LabeledTextField.java \
	JTextFieldPanel.java \
	ButtonPanel.java \
	CalibrationArea.java \
	CompInfo.java \
	DnDJTree.java \
	DragDropObject.java \
	InfoPanel.java \
	LabeledMinMaxTextField.java \
	LabeledRangeTextField.java \
	Led.java \
	LogoPanel.java \
	MSBQueryTableModel.java \
	MsbNode.java \
	OmpOM.java \
	ProgramTree.java \
	QtFrame.java \
	RadioPanel.java \
	SatPanel.java \
	SwingWorker.java \
	TableMap.java \
	TableSorter.java \
	TelescopeDataPanel.java \
	TimePanel.java \
	Timer.java \
	TimerEvent.java \
	TimerListener.java \
	XmlUtils.java \
	TrashCan.java \
	DeferredProgramList.java \
	NotePanel.java \
	UTPanel.java

include $(BUILD)/make.tail


# Phony Targets
.PHONY: clean build help

#### Help
help:
	@echo "Usage: make [targets...]"
	@echo ""
	@echo "where targets include:"
	@echo ""
	@echo "  help           display this help"
	@echo "  all            compile all (default)"
	@echo "  clean          remove all class files"
	@echo "  build          rebuild all inconditionnally"
	@echo "  <class file>   compile the given file"
	@echo "  <subdir>.make  compile the given subdir"
	@echo "  <subdir>.clean clean the given subdir"

