#### Targets settings

TOP = ../../../../../..

PACKAGE = edu/jach/qt/gui

SOURCES = \
	AIVTriplet.java \
	AVPair.java \
	AttributeEditor.java \
	AttributeOrigin.java \
	AttributeTableModel.java \
	ButtonPanel.java \
	CalibrationArea.java \
	ColumnSelector.java \
	CompInfo.java \
	DeferredProgramList.java \
	DnDJTree.java \
	DragDropObject.java \
	Execute.java \
	ExecuteJCMT.java \
	ExecuteUKIRT.java \
	HelpPage.java \
	InfoPanel.java \
	JTextFieldPanel.java \
	LabeledMinMaxTextField.java \
	LabeledRangeTextField.java \
	Led.java \
	LogoPanel.java \
	MSBQueryTableModel.java \
	MsbNode.java \
	NotePanel.java \
	OmpOM.java \
	ProgramTree.java \
	ProjectTableModel.java \
	ProjectTableSelectionModel.java \
	QtFrame.java \
	RadioPanel.java \
	SatPanel.java \
	SwingWorker.java \
	TableMap.java \
	TableSorter.java \
	TelescopeDataPanel.java \
	TimePanel.java \
	Timer.java \
	TimerEvent.java \
	TimerListener.java \
	TrashCan.java \
	TreeViewer.java \
	UTPanel.java \
	WidgetDataBag.java \
	WidgetPanel.java \
	XmlUtils.java \
	LogViewer.java

include ${TOP}/Makefile

