#### Targets settings

TOP = ../../../../../..

PACKAGE = edu/jach/qt/utils

SOURCES = \
	BasicWindowMonitor.java \
	Bench.java \
	Blocker.java \
	CalibrationList.java \
	ErrorBox.java \
	ExecDtask.java \
	InvalidUserException.java \
	HTMLViewer.java \
	LockFile.java \
	MSBDoneDialog.java \
	MsbClient.java \
	MyTreeCellRenderer.java \
	NoSuchParameterException.java \
	ObsListCellRenderer.java \
	OracColor.java \
	QtTools.java \
	SimpleMoon.java \
	SoapClient.java \
	SpClient.java \
	TelescopeInformation.java \
	TextReader.java \
	TimeUtils.java \
	Translating.java \
        UkirtTranslator.java

include ${TOP}/Makefile

