#### Targets settings

TOP = ../../../../../..

PACKAGE = edu/jach/qt/utils

SOURCES = \
	CalibrationList.java \
	MsbColumnInfo.java \
	MsbColumns.java \
	MSBTableModel.java \
	ErrorBox.java \
	ExecDtask.java \
	InvalidUserException.java \
	HTMLViewer.java \
	MsbClient.java \
	NoSuchParameterException.java \
	ObsListCellRenderer.java \
	OracColor.java \
	QtTools.java \
	SimpleMoon.java \
	TelescopeInformation.java \
	TextReader.java \
	TimeUtils.java \
	Translating.java \
        UkirtTranslator.java

include ${TOP}/Makefile

